CREATE TABLE pupil (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE subject (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE grade (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pupil_id INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    grade REAL NOT NULL,
    FOREIGN KEY(pupil_id) REFERENCES pupil(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(subject_id) REFERENCES subject(id) ON UPDATE CASCADE ON DELETE CASCADE
);
